version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:

  cdrpr:
    image: matjaz99/cdrpr:1.0
    networks:
      - net
    environment:
      - CDRPR_DIRECTORY=/opt/cdr
      - CDRPR_THREADS=3
      - CDRPR_BULK_SIZE=1000
      - CDRPR_DEBUG_ENABLED=false
      - CDRPR_ES_URL=http://mcrk-docker-1:9200/cdrs/_bulk?pretty
    deploy:
      mode: replicated
      replicas: 1
