{
 "title": "Animals on Springboot",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "by species",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(animals_by_species_3) by (species)",
     "legendFormat": "{{species}}"
    }
   ]
  },
  {
   "title": "by country",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(animals_by_species_3) by (country)",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "sum",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(animals_by_species_3)" }
   ]
  },
  {
   "title": "Avg response time [GET /animals/all]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{exception=\"None\", uri=\"/animals/all\"}[5m]) / irate(http_server_requests_seconds_count{exception=\"None\", uri=\"/animals/all\"}[5m])"
    }
   ]
  },
  {
   "title": "population by species",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(animals_by_species_4) by (species)",
     "legendFormat": "{{species}}"
    }
   ]
  },
  {
   "title": "population by country",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 9, "x": 9, "y": 6 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(animals_by_species_4) by (country)",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Avg response time [GET /animals/all]",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 6 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(animals_request_all_seconds_sum{exception=\"None\", uri=\"/animals/all\"}[5m]) / irate(animals_request_all_seconds_count{exception=\"None\", uri=\"/animals/all\"}[5m])"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "animals_by_species_3", "legendFormat": "{{country}}-{{species}}" }
   ]
  },
  {
   "title": "http_server_requests_seconds_count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "http_server_requests_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "rate http_server_requests_seconds_count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count[5m]) * 60 / 4",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "rate http_server_requests_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum[5m]) * 60 / 4",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "API Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{exception=\"None\", uri!~\".*actuator.*\"}[5m]) / irate(http_server_requests_seconds_count{exception=\"None\", uri!~\".*actuator.*\"}[5m])",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "API Response time histogram",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[5m])"
    }
   ]
  },
  {
   "title": "API Response time 0.5 quantile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket[5m])) by (uri, method, le))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "API Response time 0.9 quantile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_seconds_bucket[5m])) by (uri, method, le))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}