version: '3.6'

networks:
  monitoring-network:
    driver: overlay
    attachable: true
  another-network:
    driver: overlay
    attachable: true

configs:
  prometheus_config:
    file: ./prometheus_config/prometheus.yml
  alert_rules:
    file: ./prometheus_config/alert_rules/alert_rules.yml

secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd.conf
  grafana-db:
    file: ./secrets/grafana-db.conf

volumes:
  alertmanager_storage: {}
  postgres_storage:
    driver: local
  prometheus_storage:
    driver: local

services:

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
      - monitoring-network
      - another-network
      - and-another
    ports:
      - 9100:9100
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      # no collectors are explicitely enabled here, because the defaults are sufficient
      - '--no-collector.ipvs'

  node-exporter-2:
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
      - monitoring-network
      - another-network
      - and-another
    ports:
      - 9100:9100
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      # no collectors are explicitely enabled here, because the defaults are sufficient
      - '--no-collector.ipvs'