version: '3.6'

networks:
  monitoring-network:
    driver: overlay
    attachable: true
  #host:
  #  external: true

configs:
  prometheus_config:
    file: ./prometheus_config/prometheus.yml
  alert_rules:
    file: ./prometheus_config/alert_rules/alert_rules.yml
  recording_rules:
    file: ./prometheus_config/recording_rules/recording_rules.yml
  prometheus_targets_docker:
    file: ./prometheus_config/targets/docker_nodes.yml
  prometheus_targets_nodes:
    file: ./prometheus_config/targets/nodes.json
  node_exporter_metrics:
    file: ./node_exporter_file_collector/server_metadata_metrics.prom
  alertmanager_config:
    file: ./alertmanager_config/alertmanager.yml
  blackbox_config:
    file: ./blackbox_config/blackbox.yml
  snmp_exporter_config:
    file: ./snmp_exporter_config/snmp.yml

secrets:
  postgres-passwd:
    file: ./secrets/postgres-passwd.conf
  grafana-db:
    file: ./secrets/grafana-db.conf

volumes:
  alertmanager_storage: {}
  postgres_storage:
    driver: local
  prometheus_storage:
    driver: local

services:

  node-exporter:
    #image: prom/node-exporter:v0.17.0
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
      - monitoring-network
    ports:
      - 9100:9100
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      # no collectors are explicitely enabled here, because the defaults are sufficient
      - '--no-collector.ipvs'
    deploy:
      mode: global

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.13.0
    networks:
      - monitoring-network
      #- host
    ports:
      - 9115:9115
    #dns: 8.8.8.8
    #volumes:
    #  - "./config:/config"
    command:
      - '--config.file=/etc/blackbox_exporter/blackbox.yml'
    configs:
      - source: blackbox_config
        target: /etc/blackbox_exporter/blackbox.yml
    user: root
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  snmp-exporter:
    image: prom/snmp-exporter:v0.13.0
    networks:
      - monitoring-network
    ports:
      - 9116:9116
      - 116:116/udp
    #volumes:
    #  - /opt/monitoring/snmp-exporter:/etc/snmp_exporter
    configs:
      - source: snmp_exporter_config
        target: /etc/snmp_exporter/snmp.yml
    command:
      - '--config.file=/etc/snmp_exporter/snmp.yml'
    user: root
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  prometheus:
    image: prom/prometheus:v2.5.0
    ports:
      - 9090:9090
    networks:
      - monitoring-network
    command:
      - '--config.file=/prometheus_config/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.path=/prometheus_data'
      - '--storage.tsdb.retention=24h'
    volumes:
      - prometheus_storage:/prometheus_data
    configs:
      - source: prometheus_config
        target: /prometheus_config/prometheus.yml
      - source: alert_rules
        target: /prometheus_config/alert_rules.yml
      - source: prometheus_targets_docker
        target: /prometheus_config/targets/docker_nodes.yml
      - source: prometheus_targets_nodes
        target: /prometheus_config/targets/nodes.json
      - source: recording_rules
        target: /prometheus_config/recording_rules.yml
    user: root
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: "0.5"
          memory: 265M
        reservations:
          cpus: '0.25'
          memory: 64M
      labels:
        com.example.description: "This label will appear on the web service"

  cadvisor:
    image: google/cadvisor:v0.32.0
    networks:
      - monitoring-network
    ports:
      - 9080:8080
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global

  alertmanager:
    image: prom/alertmanager:v0.15.3
    ports:
      - 9093:9093
    networks:
      - monitoring-network
    command:
      - '--config.file=/alertmanager_config/alertmanager.yml'
      #- '--web.external-url=http://192.168.1.115:9093/'
      - '--web.external-url=http://$HOSTNAME:9093/'
      - '--cluster.listen-address=$HOSTNAME:9094'
    configs:
      - source: alertmanager_config
        target: /alertmanager_config/alertmanager.yml
    deploy:
      mode: replicated
      replicas: 1

  unsee:
    image: cloudflare/unsee:v0.9.2
    ports:
      - 9094:8080
    networks:
      - monitoring-network
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
      #- "PORT=9094"
    deploy:
      mode: replicated
      replicas: 1

  grafana:
    image: grafana/grafana:5.4.2
    networks:
      - monitoring-network
    ports:
      - 3000:3000
    environment:
      - GF_DATABASE_HOST=postgres:5432
      - GF_DATABASE_TYPE=postgres
      - GF_DATABASE_NAME=postgres
      - GF_DATABASE_USER=postgres
      - GF_DATABASE_PASSWORD__FILE=/run/secrets/postgres-passwd
      - GF_SESSION_PROVIDER=postgres
      - GF_SESSION_PROVIDER_CONFIG__FILE=/run/secrets/grafana-db
    secrets:
      - grafana-db
      - postgres-passwd
    deploy:
      mode: replicated
      replicas: 1

  postgres:
    image: postgres:11
    networks:
      - monitoring-network
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      - PGDATA=/pg_data
    secrets:
      - postgres-passwd
    volumes:
      - postgres_storage:/pg_data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.labels.db-type == postgresql
      resources:
        limits:
          memory: 1024M

#  alpine:
#    image: alpine:3.8
#    networks:
#      - monitoring-network
#    ports:
#      - 22:22
#    deploy:
#      mode: replicated
#      replicas: 1
#      placement:
#        constraints:
#        - node.hostname == docker-1
