version: '3.6'

networks:
  monitoring-network:
    driver: overlay
    attachable: true

services:

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
      - monitoring-network
      - another-network
      - and-another
    ports:
      - 9100:9100
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      # no collectors are explicitely enabled here, because the defaults are sufficient
      - '--no-collector.ipvs'
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s

  node-exporter-2:
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
      - monitoring-network
      - another-network
      - and-another
    ports:
      - 9100:9100
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      # no collectors are explicitely enabled here, because the defaults are sufficient
      - '--no-collector.ipvs'
    deploy:
      mode: global
      placement:
        constraints:
        - node.role == manager
        - node.labels.region == west
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
