version: '3.2'

services:
  minio:
    image: minio/minio:RELEASE.2020-09-10T22-02-45Z
    container_name: minio
    volumes:
      - ./data/minio:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ACCESS_KEY: myaccesskey
      MINIO_SECRET_KEY: mysecretkey
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
